import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function SMSLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
        <h1 className="text-3xl">SMS</h1>
        {children}
    </>
  )
}
